language: python
install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
