site_name: techNotes
pages:
    - Home: index.md
    - Linux: 
      - 一般问题: Linux/index.md
      - shell: shell/index.md
    - R: 
      - 一般问题: R/index.md
      - ggplot作图: R/ggplot.md
      - 案例分析: R/legend_from_zhihu.md
      - 源码安装 RMySQL: R/install-notes-for-rmysql.md
    - Programming:
      - Python: python/index.md
      - Matlab: Matlab/index.md
      - Cpp: Cpp/index.md
      - Julia: julia/index.md
      - Java: java/index.md
      - TeX: TeX/index.md
      - SQL: SQL/index.md
      - Cuda: cuda/index.md
      - PHP: PHP/index.md
    - Website:
      - Website: website/index.md
      - CSS: css/index.md
      - JS: js/index.md
    - Network: Internet/index.md
    - Tools:
      - Autotools: autotools/index.md
      - Emacs: Emacs/index.md
      - Vi: vi/index.md
      - Ssh: ssh/index.md
      - Git: Git/index.md
      - Phantomjs: phantomjs/index.md
      - Qt: Qt/index.md
    - Stats:
      - Calculus: calculus/index.md
      - Scientific: scientific/index.md
      - Graph: graph/index.md
      - Finance: finance/index.md
    - English: English/index.md
    - Mi: mi/index.md
    - Win: win/index.md
    - Links: links/index.md
    - Misc: 
      - 小程序: misc/wx.md
      - jssdk: misc/wxjssdk.md
      - 讲座: misc/report.md

theme:
  name: 'material'
  search:
    language: 'en, jp'
google_analytics: ['UA-85007363-6', 'auto']
copyright: 'Copyright &copy; 2018 weiya'
site_author: weiya
site_description: '技术博客'
site_url: https://tech.hohoweiya.xyz
extra:
  social:
    - type: 'github'
      link: 'https://github.com/szcf-weiya'
    - type: 'book'
      link: 'https://esl.hohoweiya.xyz'
    - type: 'home'
      link: 'https://hohoweiya.xyz'
    - type: 'rss'
      link: 'https://blog.hohoweiya.xyz'
    - type: 'envelope'
      link: 'mailto:szcfweiya@gmail.com'

repo_name: 'szcf-weiya/techNotes'
repo_url: 'https://github.com/szcf-weiya/techNotes'
edit_uri: ""
extra_javascript: 
  - javascripts/baiduzhanzhang.js

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - meta
  - toc:
      permalink: true
